export const GAME_CONSTANTS = {
  WORLD_WIDTH: 2400,
  WORLD_HEIGHT: 1600,
  TILE_SIZE: 32,
  PLAYER_SIZE: 24,
  PLAYER_DEPTH: 20,
  ITEM_PICKUP_RADIUS: 48,
  LOCATION_TRIGGER_RADIUS: 120,
  CHALLENGE_RADIUS: 115,
  CHALLENGE_COOLDOWN_MS: 3000,
  INVENTORY_LIMIT: 3,
  BASE_SCORE_PER_ITEM: 10
};
